export const homeContent = {
  hero: {
    heading: "Security built for the way attacks actually happen.",
    paragraphs: [
      "Attackers do not think in products, departments or compliance checklists.",
      "Neither do we.",
      "SilverFox brings together offensive security, security engineering, managed defence and threat intelligence to expose weaknesses, strengthen systems and protect organisations across the attack lifecycle.",
    ],
    microcopy: "Offensive insight. Defensive discipline. Engineering depth.",
  },
  positioning: {
    label: "ASSUMPTION",
    resolved: "EVIDENCE",
    heading: "Security should be demonstrated, not assumed.",
    paragraphs: [
      "Modern organisations operate across cloud platforms, applications, identities, endpoints, networks, third parties and increasingly complex technology stacks.",
      "A weakness in any one of them can become the beginning of an attack path.",
      "SilverFox works across those boundaries.",
      "We assess risk, challenge defences, engineer stronger environments, monitor for threats and investigate incidents when something goes wrong.",
      "Because security is not a collection of controls.",
      "It is how well those controls hold together when someone tries to break through.",
    ],
  },
  attackPath: {
    heading: "Attackers see paths. We do too.",
    path: [
      "A vulnerable application may expose an identity.",
      "A compromised identity may unlock cloud infrastructure.",
      "A misconfiguration may turn limited access into privileged access.",
      "An overlooked system may become the easiest route into everything else.",
    ],
    intro: "That is why SilverFox approaches cybersecurity as a connected problem.",
    verbs: [
      { verb: "Understand the risk.", body: "Know what matters, where exposure exists and which controls deserve attention." },
      { verb: "Challenge the defence.", body: "Test systems the way a determined adversary would." },
      { verb: "Engineer the solution.", body: "Build security into applications, infrastructure, cloud and identity." },
      { verb: "Watch the environment.", body: "Detect meaningful activity before alerts disappear into noise." },
      { verb: "Respond with evidence.", body: "Contain incidents, establish what happened and regain control." },
    ],
  },
  services: {
    heading: "Cybersecurity across the attack lifecycle.",
    intro:
      "From board-level cyber risk to deeply technical security operations, SilverFox provides specialist capabilities across six core practices.",
  },
  offensiveFeature: {
    heading: "A control that has never been tested is still an assumption.",
    paragraphs: [
      "Policies can be reviewed.",
      "Configurations can be checked.",
      "Dashboards can show green.",
      "None of that proves an attacker cannot get through.",
      "SilverFox offensive-security teams challenge applications, identities, infrastructure and detection capabilities under realistic attack conditions.",
      "We do not stop at listing vulnerabilities.",
      "We look for the path.",
    ],
    capabilities: [
      { name: "Penetration Testing", body: "Find exploitable weaknesses across applications, APIs, infrastructure, cloud and identity." },
      { name: "Red Teaming", body: "Test how technology, people and defensive processes respond to a determined adversary." },
      { name: "Purple Teaming", body: "Bring attackers and defenders together to improve detection and response." },
      { name: "AI Security Testing", body: "Challenge AI-enabled applications, LLM integrations and agentic systems before attackers do." },
      { name: "Security Validation", body: "Determine whether controls actually stop, detect and contain the techniques they were designed to address." },
    ],
    kineticFrom: "Control exists.",
    kineticTo: "Control holds.",
    cta: "Challenge Your Environment",
  },
  technologiesIntro: {
    heading: "Security technology shaped by real security problems.",
    paragraphs: ["Not another collection of dashboards.", "Three platforms.", "Three questions."],
  },
  scopeFeature: {
    heading: "Know the exposure.",
    subheading: "See your organisation from the outside in.",
    question: "Where are we exposed?",
    helpsTeams: [
      "Discover internet-facing assets",
      "Identify shadow infrastructure",
      "Monitor domains, services and certificates",
      "Detect exposed applications and cloud resources",
      "Track vulnerabilities and misconfigurations",
      "Identify credential exposure",
      "Correlate vulnerability intelligence",
      "Prioritise risk",
      "Understand attack paths",
      "Track remediation",
    ],
    primaryCta: "Explore SCOPE",
    secondaryCta: "Map Your Exposure",
  },
  signalFeature: {
    heading: "Read the signal.",
    subheading: "Turn security telemetry into decisions.",
    question: "What is happening?",
    connects: ["Endpoint", "Network", "Identity", "Cloud", "Applications", "Threat Intelligence"],
    transform: ["Detection", "Context", "Investigation", "Response"],
    kineticFrom: "Noise.",
    kineticTo: "Signal.",
    primaryCta: "Explore SIGNAL",
    secondaryCta: "Discuss SIGNAL",
  },
  rangeFeature: {
    heading: "Prove the defence.",
    subheading: "Test resilience before reality does.",
    question: "Can we withstand it?",
    mobileSteps: ["Attack", "Observe", "Improve"],
    primaryCta: "Explore RANGE",
    secondaryCta: "Build Your Cyber Range",
  },
  philosophy: {
    heading: "Know the exposure. Read the signal. Prove the defence.",
    perspectives: [
      { product: "SCOPE", body: "Know where attackers can reach." },
      { product: "SIGNAL", body: "Understand what is happening." },
      { product: "RANGE", body: "Determine whether the defence holds." },
    ],
    footnote: "Reducing uncertainty before an attacker turns it into an incident.",
  },
  engineering: {
    heading: "When the right solution does not exist, build it.",
    secureSoftware: {
      title: "Secure Software Engineering",
      items: [
        "Indigenous cybersecurity products",
        "Secure bespoke software",
        "Security automation",
        "Enterprise security platforms",
        "Command and control systems",
        "Security dashboards",
        "Intelligence platforms",
        "On-premise systems",
        "Restricted-network applications",
        "Systems integration",
      ],
    },
    intelligentSystems: {
      title: "Intelligent Systems",
      intro: "Where appropriate, our engineering teams apply:",
      items: ["Machine learning", "Behavioural analytics", "Anomaly detection", "Intelligent automation", "Computer vision", "Video analytics", "Edge inference", "Sensor fusion", "Decision-support systems"],
    },
    edge: {
      title: "Edge & Embedded",
      items: ["Edge computing", "Embedded software", "Secure device systems", "Sensor integration", "Offline processing", "Real-time analytics"],
    },
    research: {
      title: "Applied Research",
      items: ["Cybersecurity research", "Vulnerability research", "Security tool development", "AI security research", "Algorithm development", "Rapid prototyping", "Proof-of-concept development", "Technology evaluation"],
    },
    statement: "Research when necessary. Engineer when possible. Build when it matters.",
    cta: "Explore Engineering & R&D",
  },
  manifesto: {
    lineOne: "We do not sell fear.",
    lineTwo: "We engineer confidence.",
    paragraphs: [
      "Security does not improve because the dashboard looks reassuring.",
      "It improves when assumptions are challenged.",
      "When architectures are understood.",
      "When controls are tested.",
      "When telemetry becomes intelligence.",
      "When incidents produce evidence.",
      "And when weaknesses become engineering decisions.",
    ],
    closing: "Security should be demonstrated, not assumed.",
  },
  whySilverFox: [
    { heading: "Offensive insight.", body: "Understanding security from the attacker's perspective changes how defences are designed." },
    { heading: "Defensive discipline.", body: "Detection and response require engineering, context and operational consistency." },
    { heading: "Engineering depth.", body: "Finding the problem is not enough. SilverFox can help design, integrate and build the solution." },
    { heading: "Connected thinking.", body: "Cloud, identity, applications, infrastructure and data are not independent attack surfaces. Neither is our approach." },
    { heading: "Evidence over assumption.", body: "We test what can be tested, investigate what happened and explain what the evidence supports." },
    { heading: "Technology without dependency.", body: "We work across technology ecosystems and develop specialised capability where standard platforms are not enough." },
  ],
  theWay: [
    { verb: "Think like the adversary.", body: "Understand how individual weaknesses become attack paths." },
    { verb: "Question the assumption.", body: "A security control should earn confidence through evidence." },
    { verb: "Follow the signal.", body: "Prioritise what changes the security decision." },
    { verb: "Engineer the outcome.", body: "Reports identify problems. Engineering changes them." },
    { verb: "Stay curious.", body: "Attackers adapt. Technology evolves. Security cannot stand still." },
  ],
  finalCta: {
    heading: "What would an attacker find?",
    paragraphs: [
      "Your attack surface already exists.",
      "The question is how well you understand it, how effectively your controls hold and how quickly your team can act when something changes.",
      "Start with the problem that matters most.",
    ],
    primaryCta: "Talk to a Security Specialist",
    secondaryCta: "Test Your Defences",
    supportingLinks: [
      { label: "Map Your Exposure with SCOPE", href: "/technologies/scope" },
      { label: "Strengthen Your Cyber Defence", href: "/services/cyber-defence" },
      { label: "Respond to an Incident", href: "/services/incident-response" },
    ],
  },
};
