import type { ServiceContent } from "@/lib/types";

export const incidentResponse: ServiceContent = {
  slug: "incident-response",
  number: "06",
  name: "Incident Response, DFIR & Threat Intelligence",
  category: "Incident Response",
  menuDescriptor: "Contain incidents, establish what happened and turn intelligence into action.",
  signature: "When something happens, certainty matters.",
  homepage: {
    descriptor:
      "Cyber incidents create pressure, incomplete information and difficult decisions. SilverFox helps organisations contain threats, establish what happened, determine what remains at risk and move from incident to recovery with evidence rather than assumption.",
    capabilities: [
      "Emergency incident response",
      "Ransomware response",
      "Data-breach investigation",
      "Business email compromise",
      "Malware incidents",
      "Cloud incident response",
      "Insider-threat investigation",
      "Digital forensics",
      "Endpoint, network and memory forensics",
      "Malware analysis",
      "Compromise assessments",
      "APT investigations",
      "IOC hunting",
      "Threat actor profiling",
      "MITRE ATT&CK analysis",
      "Vulnerability intelligence",
      "Dark-web intelligence",
      "Incident-response retainers",
    ],
  },
  primaryCta: "Respond to an Incident",
  secondaryCta: "Discuss an Incident Response Retainer",
  overviewCta: "Explore Incident Response",
  hero: {
    paragraphs: [
      "Cyber incidents create pressure, incomplete information and difficult decisions.",
      "SilverFox helps organisations contain threats, reconstruct what happened, determine what remains at risk and move from incident to recovery with evidence rather than assumption.",
    ],
  },
  sections: [
    {
      id: "pressure-clarity",
      heading: "Pressure makes clarity more important.",
      paragraphs: ["During an incident, leadership and technical teams need reliable answers:"],
      questions: [
        "Is the attacker still active?",
        "Which systems and identities are affected?",
        "How did the incident begin?",
        "What did the attacker access?",
        "Which evidence must be preserved?",
        "What can be contained safely?",
        "What remains at risk?",
        "What should happen next?",
      ],
      footnote: [
        "SilverFox brings incident coordination, technical investigation, forensics and threat context together.",
      ],
    },
    {
      id: "incident-response-capability",
      heading: "Incident Response",
      subheading: "Contain the threat and regain control.",
      paragraphs: ["SilverFox can support incidents including:"],
      groups: [
        {
          heading: "Incident types",
          items: [
            "Ransomware",
            "Data breaches",
            "Business email compromise",
            "Malware infections",
            "Cloud compromise",
            "Identity compromise",
            "Insider threats",
            "Web application compromise",
            "Unauthorised access",
            "Suspected advanced threat activity",
            "Third-party compromise",
            "Destructive attacks",
          ],
        },
        {
          heading: "Response capabilities",
          items: [
            "Emergency cyber incident response",
            "Incident triage",
            "Technical scoping",
            "Containment planning",
            "Evidence preservation",
            "Eradication support",
            "Recovery guidance",
            "Stakeholder coordination",
            "Executive technical briefings",
            "Post-incident review",
          ],
        },
      ],
    },
    {
      id: "digital-forensics",
      heading: "Digital Forensics",
      subheading: "Establish what the evidence supports.",
      paragraphs: ["Digital forensics can include:"],
      groups: [
        {
          items: [
            "Endpoint forensics",
            "Server forensics",
            "Network forensics",
            "Memory forensics",
            "Mobile forensics",
            "Cloud forensics",
            "Email forensics",
            "Log analysis",
            "Timeline reconstruction",
            "Deleted-artifact recovery where possible",
            "Root-cause investigation",
            "Evidence preservation and documentation",
          ],
        },
      ],
      footnote: [
        "Forensic conclusions should distinguish confirmed evidence, reasonable inference and unanswered questions.",
      ],
    },
    {
      id: "malware-analysis",
      heading: "Malware Analysis",
      paragraphs: ["SilverFox can analyse suspicious software to understand:"],
      groups: [
        {
          items: [
            "behaviour",
            "capabilities",
            "persistence",
            "command and control",
            "configuration",
            "indicators of compromise",
            "propagation",
            "impact",
            "relationships with known malware or campaigns",
          ],
        },
      ],
      footnote: [
        "Analysis may include static, dynamic and reverse-engineering techniques within an appropriate controlled environment.",
      ],
    },
    {
      id: "compromise-assessment",
      heading: "Compromise Assessment",
      subheading: "Determine whether the environment has already been breached.",
      paragraphs: ["Compromise assessments may include:"],
      groups: [
        {
          items: [
            "enterprise-wide threat hunting",
            "IOC hunting",
            "persistence discovery",
            "suspicious identity analysis",
            "endpoint investigation",
            "cloud investigation",
            "network evidence review",
            "APT investigation",
            "historical compromise analysis",
            "scoping of affected systems and accounts",
          ],
        },
      ],
    },
    {
      id: "threat-intelligence",
      heading: "Threat Intelligence",
      subheading: "Intelligence should change a decision.",
      paragraphs: ["SilverFox can develop and apply:"],
      groups: [
        {
          items: [
            "Strategic threat intelligence",
            "Operational threat intelligence",
            "Tactical threat intelligence",
            "Threat actor profiling",
            "Campaign tracking",
            "Tactics, techniques and procedures analysis",
            "MITRE ATT&CK mapping",
            "Vulnerability intelligence",
            "Malware intelligence",
            "Indicator analysis",
            "Dark-web intelligence",
            "Intelligence requirements and reporting",
          ],
        },
      ],
      footnote: [
        "Threat intelligence is most useful when connected to exposure, detection, investigation and response.",
      ],
    },
    {
      id: "ir-retainers",
      heading: "Incident Response Retainers",
      subheading: "Prepare the relationship before the incident.",
      paragraphs: ["A retainer can establish:"],
      groups: [
        {
          items: [
            "contact and escalation routes",
            "response expectations",
            "organisational context",
            "access requirements",
            "evidence-handling procedures",
            "key stakeholders",
            "technical prerequisites",
            "periodic readiness reviews",
            "agreed response support",
          ],
        },
      ],
      footnote: ["The objective is to reduce avoidable delay when an incident occurs."],
    },
  ],
  approach: [
    {
      step: "01",
      title: "Stabilise",
      body: "Establish communication, immediate priorities and a controlled response structure.",
    },
    {
      step: "02",
      title: "Scope",
      body: "Identify affected systems, identities, data and business processes.",
    },
    {
      step: "03",
      title: "Investigate",
      body: "Collect and analyse evidence to reconstruct activity and determine impact.",
    },
    {
      step: "04",
      title: "Contain",
      body: "Limit attacker access while considering operational and evidential consequences.",
    },
    {
      step: "05",
      title: "Eradicate",
      body: "Remove persistence, malicious tooling, compromised access and root causes.",
    },
    {
      step: "06",
      title: "Recover",
      body: "Restore operations with appropriate validation and monitoring.",
    },
    {
      step: "07",
      title: "Improve",
      body: "Turn incident evidence into stronger architecture, identity controls, detections and response plans.",
    },
  ],
  extra: [
    {
      id: "incident-to-improvement",
      heading: "From Incident to Improvement",
      paragraphs: ["An investigation should strengthen the environment.", "Evidence may drive:"],
      groups: [
        {
          items: [
            "new detections",
            "improved logging",
            "identity remediation",
            "architecture changes",
            "hardening",
            "vulnerability remediation",
            "updated response playbooks",
            "targeted penetration testing",
            "threat hunting",
            "RANGE exercises",
          ],
        },
      ],
      footnote: ["This creates a closed loop:"],
      sequence: ["Incident", "Evidence", "Remediation", "Validation"],
    },
  ],
  relatedTechnology: [
    {
      product: "SIGNAL",
      body: "SIGNAL can connect telemetry, entities, timelines, investigations and threat intelligence.",
    },
    {
      product: "RANGE",
      body: "RANGE can reproduce scenarios, support DFIR training and validate updated response plans in a controlled environment.",
    },
    {
      product: "SCOPE",
      body: "SCOPE can help identify relevant external exposure and prioritise remediation after an incident.",
    },
  ],
  relevantFor: [
    "Organisations facing an active or suspected compromise",
    "Enterprises with incident-response obligations",
    "Financial services",
    "Government and defence",
    "Critical infrastructure",
    "Cloud-heavy organisations",
    "Businesses exposed to ransomware or business email compromise",
    "Organisations seeking a response retainer",
  ],
  closing: {
    heading: "Contain the threat. Establish the facts. Regain control.",
    paragraphs: ["When the situation is uncertain, act from evidence."],
    cta: "Respond to an Incident",
  },
};
